---
title: "Gardnerella mapping vs. MetaPhlAn Results"
author: "Hanna Berman"
date: "4/30/2021"
output: html_document
---

# Set up
## Packages
```{r}
library(tidyverse)
library(formattable)
library(ggpubr)
library(cowplot)
theme_set(theme_bw())
```

## File Paths
```{r, message=FALSE, warning=FALSE}
figureOut <- "/Volumes/GoogleDrive-103667279570938865306/My Drive/Callahan Lab/metagenome_gardnerella/FIGURES/V5_manuscript_figures/gardnerella_mapping"
```


## Abundance
### Stanford UAB Data
```{r}
#Metaphlan Aabundance:
suMetaphlanPath <- "../../humann2/merged_tables/mergedMetaphlanAbundance.tsv"
sumDF <- suMetaphlanPath %>%
  read_tsv() %>%
  filter(str_detect(ID, "s__"), !str_detect(ID, "t__")) %>%
  mutate(Species = str_extract(ID, "(?<=s__)\\w+$")) %>%
  select(Species, everything(), -ID) %>%
  as.data.frame() %>%
  dplyr::rename_at(2:ncol(.), ~str_extract(.x, "[0-9]{10}")) %>%
  column_to_rownames(var="Species") %>%
  t %>%
  as.data.frame() %>%
  mutate_all(funs(./100)) %>%
  rownames_to_column(var="SampleID")
sumDF[1:6,1:5]

sumetaphlanGardAbundance <- sumDF %>%
  select(SampleID, Gardnerella_vaginalis) %>%
  dplyr::rename(metaphlanGardAbundance=Gardnerella_vaginalis)

# Mapping Abundance
sumapCladeAbundance <- "../gardCladeRelativeAbundance.tsv" %>%
  read_tsv()
head(sumapCladeAbundance)
```

### HMP2 data
```{r}
#Metaphlan Aabundance:
hmp2MetaphlanPath <- "../../humann2/merged_tables/hmp2mgs_mergedMetaphlanAbundance.tsv"
hmp2mDF <- hmp2MetaphlanPath %>%
  read_tsv() %>%
  filter(str_detect(ID, "s__"), !str_detect(ID, "t__")) %>%
  mutate(Species = str_extract(ID, "(?<=s__)\\w+$")) %>%
  select(Species, everything(), -ID) %>%
  as.data.frame() %>%
  dplyr::rename_at(2:ncol(.), ~str_extract(.x, "[0-9]{7}")) %>%
  column_to_rownames(var="Species") %>%
  t %>%
  as.data.frame() %>%
  mutate_all(funs(./100)) %>%
  rownames_to_column(var="SampleID")
hmp2mDF[1:6,1:5]

hmp2metaphlanGardAbundance <- hmp2mDF %>%
  select(SampleID, Gardnerella_vaginalis) %>%
  dplyr::rename(metaphlanGardAbundance=Gardnerella_vaginalis)

# Mapping Abundance
hmp2mapCladeAbundance <- "../hmp2gardCladeRelativeAbundance.tsv" %>%
  read_tsv()
head(hmp2mapCladeAbundance)
```

### Join
```{r}
mapCladeAbundance <- full_join(sumapCladeAbundance, hmp2mapCladeAbundance, by = c("SampleID", "Clade", "n", "propClade"))

metaphlanGardAbundance <- full_join(sumetaphlanGardAbundance, hmp2metaphlanGardAbundance, by = c("SampleID", "metaphlanGardAbundance"))
```


### Alignments
  Mapping
```{r}
suMappingAlignments <- read_tsv("cladeAlignmentsFinal.tsv")

hmp2MappingAlignments <- read_tsv("./hmp2cladeAlignmentsFinal.tsv")

mapCladeCounts <- suMappingAlignments %>%
  full_join(hmp2MappingAlignments) %>%
  group_by(SampleID) %>%
  count(Clade)
head(mapCladeCounts)

mapGardCounts <- mapCladeCounts %>%
  group_by(SampleID) %>%
  summarise(mapReads=sum(n)) %>%
  mutate(SampleID=as.character(SampleID))
head(mapGardCounts)  
```

  Metaphlan
```{r, message=FALSE}
hmp2metaphlanGardCounts <- "./hmp2mgs_gardMarkerCounts.csv" %>%
  read_csv %>%
  mutate(SampleID=str_extract(SampleID, "(?<=SRR)[0-9]{7}"))


sumetaphlanGardCounts <- "./stanUAB_gardMarkerCounts.csv" %>%
  read_csv %>%
  mutate(SampleID=as.character(SampleID))

metaphlanGardCounts <- full_join(sumetaphlanGardCounts, hmp2metaphlanGardCounts)
nrow(metaphlanGardCounts)
```

```{r}
#compareDF <- data.frame(SampleID=missingMetaphlan, # add missing rows
#                        metaphlanReads=0) %>%
#  rbind(., metaphlanGardCounts) %>%
#  full_join(mapGardCounts, by="SampleID") %>%
#  replace_na(list(mapReads=0)) %>%
#  full_join(metaphlanGardAbundance, by="SampleID")


compareDF <- metaphlanGardCounts %>%
  full_join(mapGardCounts, by="SampleID") %>%
  full_join(metaphlanGardAbundance, by="SampleID") %>%
  replace_na(list(metaphlanReads=0, metaphlanGardAbundance=0, mapReads=0))
head(compareDF)

anyNA(compareDF$metaphlanGardAbundance)
```

# Compare alignments
 Reads vs. Reads
```{r}
compareDF %>%
  ggplot(aes(x=mapReads, y=metaphlanReads)) +
  geom_abline(color="grey", linetype=2) +
  geom_point(alpha=0.75, size=2) +
  geom_smooth(method="lm", se=FALSE, color="blue", linetype=1) +
  stat_cor(method = "pearson", alternative = "greater", label.sep = "\n") + 
  xlim(0,1000000) +
  coord_fixed() +
  labs(x=bquote('Aligned'~italic("Gardnerella") ~'Marker Reads - Our Method'), y=bquote('Aligned'~italic("Gardnerella") ~'Marker Reads - Metaphlan2'))
```

  
```{r, message=FALSE, warning=FALSE}
readsVreadsPlot <- compareDF %>%
  ggplot(aes(x=mapReads, y=metaphlanReads)) +
  geom_abline(color="grey", linetype=2) +
  geom_point(alpha=0.5, size=2) +
  geom_smooth(method="lm", se=FALSE, color="blue", linetype=1) +
  stat_cor(method = "pearson", alternative = "greater", label.sep = "\n") + 
  labs(x=bquote('Aligned'~italic("Gardnerella") ~'Marker Reads - Our Method'), y=bquote('Aligned'~italic("Gardnerella") ~'Marker Reads - Metaphlan2'))
```
  Reads vs Gardnerella abundance
```{r, message=FALSE, warning=FALSE}
abVreadsPlot <- compareDF %>%
  ggplot(aes(x=mapReads, y=metaphlanGardAbundance)) +
  geom_point(alpha=0.5, size=2) +
  geom_smooth(method="lm", se=FALSE, color="blue", linetype=1) +
  stat_cor(method = "pearson", alternative = "greater", label.sep = "\n", label.x = 20000, label.y = 0.125)  +
  ylim(0,1) +
  labs(x=bquote('Aligned'~italic("Gardnerella") ~'Marker Reads - Our Method'), y=bquote(italic("Gardnerella") ~'Relative Abundance - MetaPhlAn2'))
```

## Figure 2DE: Gardnerella mapping vs MetaPhlAn
```{r, message=FALSE, warning=FALSE, fig.width=5, fig.height=2}
plot_grid(readsVreadsPlot, abVreadsPlot, nrow=1, labels = c("D", "E"), label_size = 15)
#ggsave(filename = file.path(figureOut, paste(Sys.Date(), "Figure2DE_mappingVsMetaphlan.png", sep="_")))
```

# Session info
```{r}
#save.image("/Users/hlberman/Desktop/saveImage.Rdata")
#load("/Users/hlberman/Desktop/saveImage.Rdata")
sessionInfo()
```