---
title: "gardPresenceVsMetadata"
author: "Hanna Berman"
date: "2/14/2019"
output: html_document
---

# Setup
##Load packages
```{r libraries, warning=FALSE}
library(tidyverse); packageVersion("tidyverse")
library(phyloseq); packageVersion("phyloseq")
library(ggpubr) ; packageVersion("ggpubr")
library(tables); packageVersion("tables")
library(epitools)
`%!in%` = Negate(`%in%`)
```

## Define file paths
```{r}
input_dir <- <specify input dir>
PS_path <- file.path(input_dir, "PS_RData")
metaphlanPS <- file.path(PS_path, "metaphlan_PS.RData")
brackenPS <- file.path(PS_path, "bracken_PS.RData")
sixteenSPS <- file.path(PS_path, "16S_PS.RData")
output_dir <- <specify output dir>
df_path <- file.path(input_dir, "shotgunMetadata.tsv")
```

## load PS objects and dataframe
```{r}
load(file=metaphlanPS)
load(file=brackenPS)
load(file=sixteenSPS)
df <- read.table(df_path, sep="\t", header=TRUE, stringsAsFactors = FALSE)
```

# Gard Dominance vs. PTB (by sample)
```{r}
tableGardMax <- function(PS){
  PS0 <- PS %>%
    psmelt()
  PS1 <- PS0 %>%
    aggregate(data=., Abundance~SampleID, max) %>%
    left_join(PS0[,c("SampleID", "SubjectID", "Genus", "Abundance", "TermPre", "UAB", "PaperCohort")], by=c("Abundance", "SampleID")) %>% 
    mutate(GardMax=case_when(Genus=="Gardnerella"~"Yes",
                             Genus!="Gardnerella"~"No"))
  tab <- table(GardMax=PS1$GardMax, Preterm=PS1$TermPre)
  PC <- xtabs(~ GardMax + TermPre + PaperCohort, PS1)
  UAB <- xtabs(~ GardMax + TermPre + UAB, PS1)
  return(list(`All`=tab, `By Paper Cohort`=PC, `By Cohort`=UAB))
}
```

## Based on 16S Data
```{r}
tableBy16S <- tableGardMax(PS_16S)
tableBy16S
```

## Based on Metaphlan Data
```{r}
tableByMetaphlan <- tableGardMax(PS_metaphlan_all)
tableByMetaphlan
```

## Based on Bracken Data
```{r}
tableByBracken <- tableGardMax(PS_bracken_all)
tableByBracken
```

# Max taxon per sample by method
```{r}
A <- PS_16S %>%
  psmelt()
B <- PS_metaphlan_all %>%
  psmelt()
C <- PS_bracken_all %>%
  psmelt()

A0 <- A %>%
    aggregate(data=., Abundance~SampleID_a, max) %>%
    left_join(A[,c("SampleID_a", "Genus", "Abundance")], by=c("Abundance", "SampleID_a")) %>%
    rename(AmplicGenus=Genus, AmplicAbundance=Abundance)
B0 <- B %>%
    aggregate(data=., Abundance~SampleID_a, max) %>%
    left_join(B[,c("SampleID_a", "Genus", "Abundance")], by=c("Abundance", "SampleID_a")) %>%
    rename(MetaphlGenus=Genus, MetaphlAbundance=Abundance)
C0 <- C %>%
    aggregate(data=., Abundance~SampleID_a, max) %>%
    left_join(C[,c("SampleID_a", "Genus", "Abundance")], by=c("Abundance", "SampleID_a")) %>%
    rename(BrackGenus=Genus, BrackAbundance=Abundance)

DominantTaxa <- A0 %>%
  full_join(B0, by="SampleID_a") %>%
  full_join(C0, by="SampleID_a")
write_csv(DominantTaxa, file.path(output_dir, "dominantTaxa.csv"))
```

# Asses by "G2" 
## Add what samples are G2 vs not
```{r}
G2samples <- c("1060801198", "4007535238", "1005601098", "1005601348", "1005601168", "1062601258", "1003101188", "1003101278", "1900401198", "1062601228", "1062101108", "1062101338", "1062101238", "4007235278", "4007235168", "1003101118", "1062601368", "4007535198", "1060801338", "1060835148", "4005935278", "1061235118", "4007535358", "1050835178", "1060435348", "4002101298", "1060435318")

nG2 <- length(G2samples)

G2df <- DominantTaxa %>% #add whether the dominant gard strain is G2 (based on this first test of strainphlan)
  left_join(df[,c("SampleID_a", "SampleID", "TermPre")], by="SampleID_a") %>%
  mutate(GardDomMet=case_when(MetaphlGenus=="Gardnerella"~TRUE,
                              MetaphlGenus!= "Gardnerella"~FALSE)) 
G2df0 <- G2df %>%
  mutate(G2strain=case_when(SampleID %in% G2samples~TRUE, 
                            SampleID %!in% G2samples~FALSE)) %>%
  left_join(df[,c("SampleID", "UAB")], by="SampleID")
#test number of G2 strains
length(G2df0$G2strain[G2df0$G2strain==TRUE]) == nG2
```

##G2 strains vs PTB or Gardnerella dominance
```{r}
epitab(G2df0$G2strain, G2df0$TermPre, method = "oddsratio")
epitab(G2df0$GardDomMet, G2df0$TermPre, method = "oddsratio")
epitab(G2df0$G2strain, G2df0$GardDomMet, method = "oddsratio")

epitab(G2df0$GardDomMet[G2df0$G2strain==TRUE], G2df0$TermPre[G2df0$G2strain==TRUE], method = "oddsratio")
epitab(G2df0$GardDomMet[G2df0$G2strain==FALSE], G2df0$TermPre[G2df0$G2strain==FALSE], method = "oddsratio")
```

Session Info
```{r}
sessionInfo()
```